#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import os

import random
import datetime
import argparse

import pygame
from pygame.locals import *
from OpenGL.GL import *
from OpenGL.GLU import *

from rubik_cube import Rubik_cube
from rubik_tetrahedron import Rubik_tetrahedron
from randomize_rubik import randomize,inverser
from pygame_gestion_clavier import Gestion_clavier

def main_parser():

    parser = argparse.ArgumentParser(description='')
    parser.set_defaults(random=0)
    parser.set_defaults(cube=False)
    parser.set_defaults(tetrahedron=False)
    parser.set_defaults(exhibition=False)

    parser.add_argument('-c','--cube'  ,help='affiche Rubik\'s Cube'       ,dest="cube"        ,action='store_true')
    parser.add_argument('-t','--tetra' ,help='affiche Rubik\'s Tetrahedron',dest="tetrahedron" ,action='store_true')
    parser.add_argument('-r','--rand'  ,help='RANDOM est le nombre de transformations donné'   ,dest="random")
    parser.add_argument('-s','--show'  ,help='affiche une séquence d\'exhibition (boucle infinie)',dest="exhibition",action='store_true')

    if len(sys.argv)==1:
        parser.print_help()
        sys.exit(1)
    args = parser.parse_args()

    return args

def text_to_screen(screen, text, x, y, size = 100,color = (200, 100, 100), font_type = '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'):
    try:

        text = str(text)
        font = pygame.font.Font(font_type, size)
        text = font.render(text, True, color)
        screen.blit(text, (x, y))

    except Exception, e:
        print 'Font Error, saw it coming'
        raise e


if __name__=='__main__':

    separator=60*"="
    now = datetime.datetime.now()

    print separator
    print now.strftime("%Y-%m-%d %H:%M")
    print "auteurs : Guillaume Roux / Filipe Vasconcelos "
    print "ESME Sudria Lille "
    print separator


    args = main_parser()
    cube=args.cube
    tetrahedron=args.tetrahedron
    random_rubik=int(args.random)
    exhibition=args.exhibition


    # pygame
    pygame.init()
    display = (1200,600)
    infopygame = pygame.display.Info()

    os.environ['SDL_VIDEO_WINDOW_POS'] = "%d,%d" % (infopygame.current_w,infopygame.current_h)
    screen = pygame.display.set_mode(display, DOUBLEBUF|OPENGLBLIT)
    pygame.display.set_caption('Rubik Pygame/GL Code --- ESME Sudria Lille')

    
    # fmv : en fait cette valeur est bien trop basse à 1
    # vitesse de rotation de la caméra
    pas_rotation_camera = 10 
    # Pour tester quand une opération est complète; voir ci-après
    taux_transition_operation = 0 
    # pas de rotation pour les operations/transformation 
    # fmv : 20% c'est pas mal chez moi
    # correspond à la varible u dans transformer_rubik
    pas_rotation_operation = 0.2

    # classe gestion clavier global qq soit le polyedre
    gestion_clavier=Gestion_clavier()

    if cube :
        print "" 
        print separator 
        print "                     RUBIK'S CUBE           "
        print separator
        print "                                "
        print " affichage et gestion du clavier:"
        print " touches : "
        print 
        print " transformation : "
        print " [esy]   : rotation autour de Y "
        print " [rdx]   : rotation autour de X "
        print " [tfc]   : rotation autour de Z "
        print 
        print " mouvement caméra fleche/[pm]:"
        print " [a]     : position d'origine de la caméra"
        print 
        print " [q]     : quitter"
        print 
        print separator
        # instanciation du Rubik_cube
        rubik = Rubik_cube(ratio=display[0]/display[1])
        rubik.gerer_affichage(gestion_clavier)
        # pyOpenGl
        gluPerspective(45, rubik.ratio, 0.1, 50.0)
        glTranslatef(0.0,0.0,-30) 
        glEnable(GL_DEPTH_TEST) # Permet de cacher les objets placés derrière d'autres objets

    if tetrahedron :
        print "" 
        print separator 
        print "                     RUBIK'S TETRAHEDRON      "
        print separator
        print "                                "
        print " affichage et gestion du clavier:"
        print " touches : "
        print 
        print " transformation : "
        print " [esy]   : rotation autour de GA"
        print " [rdx]   : rotation autour de GB"
        print " [tfc]   : rotation autour de GC"
        print " [zgv]   : rotation autour de GD"
        print 
        print " mouvement caméra fleche/[pm]:"
        print " [a]     : position d'origine de la caméra"
        print ""
        print " [q]     : quitter"
        print 
        print separator
        # instanciation du Rubik_tetrahedron
        rubik = Rubik_tetrahedron(ratio=display[0]/display[1])
        rubik.gerer_affichage(gestion_clavier)
        # pyOpenGl
        gluPerspective(45, rubik.ratio, 0.1, 50.0)
        glTranslatef(0.0,0.0,-8) 
        glEnable(GL_DEPTH_TEST) # Permet de cacher les objets placés derrière d'autres objets

    # randomize
    if random_rubik > 0:
        print separator 
        print "appel de la fonction randomize"
        print random_rubik," operations/transformations"
        print separator 
        ops=randomize(rubik,random_rubik)
        for op in ops:
            rubik.operations_queue.append(op)

    if exhibition:
        print separator 
        print "                    EXHIBITION MODE"
        print separator 
        ops_random=randomize(rubik,100)

        textString=""" ESME SUDRIA Lille 
                                Labo d'informatique.
                                Auteurs : Guillaume Roux / Filipe Vasconcelos\n
                    """

    # ===================
    #   main event loop
    # ===================
    print "Running rubik ..."
    while True:

        # Gestion des événements clavier
        for event in pygame.event.get(): gestion_clavier.check_event_key(event)
       
        if not exhibition :
            # Mouvements de la caméra
            if gestion_clavier.fleche_gauche: glRotatef(pas_rotation_camera, 0, 1, 0)
            if gestion_clavier.fleche_droite: glRotatef(-pas_rotation_camera, 0, 1, 0)
            if gestion_clavier.fleche_haut:   glRotatef(pas_rotation_camera, 1, 0, 0)
            if gestion_clavier.fleche_bas:    glRotatef(-pas_rotation_camera, 1, 0, 0)
            if gestion_clavier.touche_p:      glRotatef(pas_rotation_camera, 0, 0, 1)
            if gestion_clavier.touche_m:      glRotatef(-pas_rotation_camera, 0, 0, 1)
        else:
            glRotatef(1, 1., 1., 1.)

        text_to_screen(screen, textString, 1000,400)
        # ======================================
        # Gestion des animations des opérations
        # ======================================
        if taux_transition_operation == 0:
            # Si une opération est dans la queue
            if(len(rubik.operations_queue) > 0): 
                operation_courante = rubik.operations_queue.pop(0)
                taux_transition_operation += pas_rotation_operation
        # >= (1 + pas_rotation_camera) en réalité, mais on gagne un calcul
        elif taux_transition_operation >= 1.+pas_rotation_operation:
            # Plus besoin de tourner, la transformation est finie
            taux_transition_operation = 0 
        else:
            rubik.transformer_rubik(op=operation_courante,u=pas_rotation_operation)
            taux_transition_operation += pas_rotation_operation
        if exhibition :
            op=random.choice(ops_random)
            rubik.operations_queue.append(op)

            

        # Mise à jour de l'affichage
        glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT)

        rubik.afficher()
        pygame.display.flip()

        #pygame.time.wait(10) # Enlevable
